### PR TITLE
Fix #841

### PR DESCRIPTION
**Pull request by mocchira**
Fix for https://github.com/leo-project/leofs/issues/841

### CODE REVIEW

**Comment by yosukehara** [comment]
@mocchira the test case has been not passed for three straight times as below:

```log
=ERROR REPORT==== 21-Sep-2017::11:12:25 ===
** State machine leo_compact_worker_0 terminating
** Last message in was {'$gen_sync_event',
                           {<0.2066.0>,#Ref<0.0.1.19278>},
                           {compaction_event_info,undefined,run,<0.2066.0>,
                               undefined,false,false,false,
                               #Fun<leo_object_storage_api_tests.143.17770642>}}
** When State == idling
**      Data  == {compaction_worker_state,leo_compact_worker_0,
                     leo_object_storage_0,leo_object_storage_read_0,
                     leo_metadata_0,
                     {backend_info,undefined,<<>>,<<>>,[],[],undefined,
                         undefined},
                     undefined,leo_diagnosis_log_0,idling,false,false,false,
                     false,false,100,300,0,50,150,10,
                     {compaction_prms,<<>>,<<>>,
                         {metadata_3,<<>>,0,0,0,<<>>,0,0,0,0,0,0,0,0,0,
                             undefined,0,0,0,0,0,0},
                         0,0,undefined,0,0,0,0},
                     {compaction_skip_garbage,<<>>,0,512,false,false},
                     0,0,undefined,[],undefined}
** Reason for termination =
** {{db_open,"IO error: lock /home/yosuke/dev/projects/leo-project/leofs/deps/leo_object_storage/.eunit/comaction_test/avs1/metadata/0_63673179145//LOCK: Resource temporarily unavailable"},
    {gen_server,call,[leo_metadata_0,run_compaction,30000]}}

=CRASH REPORT==== 21-Sep-2017::11:12:25 ===
  crasher:
    initial call: leo_compact_fsm_worker:init/1
    pid: <0.1999.0>
    registered_name: leo_compact_worker_0
    exception exit: {{db_open,"IO error: lock /home/yosuke/dev/projects/leo-project/leofs/deps/leo_object_storage/.eunit/comaction_test/avs1/metadata/0_63673179145//LOCK: Resource temporarily unavailable"},
                     {gen_server,call,[leo_metadata_0,run_compaction,30000]}}
      in function  gen_fsm:terminate/7 (gen_fsm.erl, line 626)
    ancestors: [leo_object_storage_sup,<0.1954.0>]
    messages: []
    links: [#Port<0.56777>,<0.1955.0>,#Port<0.56772>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 15378
  neighbours:
```

**Comment by mocchira** [comment]
@yosukehara 

> /home/yosuke/dev/projects/leo-project/leofs/deps/leo_object_storage/.eunit/comaction_test/avs1/metadata/0_63673179145//LOCK: Resource temporarily unavailable

It seems the existing directory - compaction_test under .eunit may cause this problem. how about make eunit after removing -rf .eunit/compaction_test ? If this works for you, we may have to add some clean up code into test suites.

**Comment by yosukehara** [comment]
@mocchira After removing `.eunit/`, It works fine.

> we may have to add some cleanup code into test suites.

To avoid test case failure, we need to implement the cleanup code.

**Comment by mocchira** [comment]
@yosukehara PTAL.

**Comment by yosukehara** [comment]
@mocchira Merged, thanks

**Pull request merged**
